### ISSUE TITLE
Update pypeteer to 0.0.25 to fix cannot import name 'chromium_executable'

### ISSUE THREAD

**Issue by parejadan** [mikeyy/nonoCAPTCHA#48]
### Problem

![capture](https://user-images.githubusercontent.com/11270882/52906533-a8434f00-321b-11e9-9989-b026c0059332.PNG)

craps out due to working with `pyppeteer` version `0.0.23` which had a typo with for `chromium_excutable` (missing `e` between `ex` and `cu`). 
https://github.com/mikeyy/nonoCAPTCHA/blob/master/requirements.txt#L10

### Solution

update to `pypeteer` to version `0.0.25` https://github.com/miyakogi/pyppeteer/commit/6106a6b9c07b7a856505081006cc5746b8cfbeff

### Reference

- got fixed on https://github.com/parejadan/nonoCAPTCHA/commit/70d00991cbcee1b5495fdb0c2255b823dbe33a94

**Comment by mikeyy** [comment]
Thank you for bringing this to my attention. I've applied the necessary changes in the latest push.

**Comment by parejadan** [comment]
@mikeyy what's keeping you from just upgrading the pypetteer version to pyppeteer==0.0.25 instead of conforming to the 0.23 typo?

asking because currently trouble shooting env setup on Windows WSL (and maybe using 0.25 is the cause of it). 


The only major changes between 0.23 and 0.25 are the typos highlighted on this github issue.

**Comment by mikeyy** [comment]
@parejadan 

Sorry, maybe you've overlooked but this is what I've done.

https://github.com/mikeyy/nonoCAPTCHA/commit/894b89fe55e0e609209db80b92d926f037ad9c03

**Comment by parejadan** [comment]
yup nvm code looks good. Sorry, similar commit name through mew off


![1](https://user-images.githubusercontent.com/11270882/52920037-5f9c9c00-32d6-11e9-9dac-fa3d1c2e11d5.PNG)
![2](https://user-images.githubusercontent.com/11270882/52920038-5f9c9c00-32d6-11e9-90b8-a11eec3f5f22.PNG)
![3](https://user-images.githubusercontent.com/11270882/52920039-5f9c9c00-32d6-11e9-8c29-8dcdacff5b8d.PNG)

**Comment by mikeyy** [comment]
That's my mistake, I was lacking any imagination for a new title. Whoops! :)
